import { test, expect } from '@playwright/test'
test('reduced-motion workflow is accessible, responsive, and avoids 3D download', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  const requests: string[] = []
  const errors: string[] = []
  page.on('request', request => requests.push(request.url()))
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Your next lead.')
  const stage = page.getByRole('button', { name: '03 Proposal building' })
  await stage.focus()
  await page.keyboard.press('Enter')
  await expect(stage).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.nexus-description')).toContainText('review')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '01 Lead qualification' })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('canvas')).toHaveCount(0)
  expect(requests.some(url => url.includes('NexusScene'))).toBe(false)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Explore the workflow' }).click()
  await expect(page).toHaveURL(/#solution$/)
  expect(errors).toEqual([])
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: `test-results/${test.info().project.name}-hero.png`, fullPage: true })
})
test('WebGL failure keeps stage controls available', async ({ page }) => {
  await page.addInitScript(() => { HTMLCanvasElement.prototype.getContext = (() => null) as typeof HTMLCanvasElement.prototype.getContext })
  await page.goto('/')
  await page.getByRole('button', { name: '04 Conversion' }).click()
  await expect(page.locator('.nexus-description')).toContainText('booking')
  await expect(page.locator('.nexus-static')).toBeVisible()
})
test('animated scene renders and can be switched to static', async ({ page }) => {
  await page.goto('/')
  await expect(page.locator('canvas')).toBeVisible({ timeout: 20000 })
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))))
  await page.screenshot({ path: `test-results/${test.info().project.name}-animated.png` })
  await page.getByRole('button', { name: 'Static view' }).click()
  await expect(page.locator('canvas')).toHaveCount(0)
  await expect(page.locator('.nexus-static')).toBeVisible()
})
